FROM oven/bun:1.1.24-alpine

WORKDIR /app

COPY package.json bun.lockb ./

ENV NODE_ENV=production

RUN bun install --frozen-lockfile --production

COPY . .

ARG BUILD_HASH
ENV APP_BUILD_HASH=${BUILD_HASH}

ENV APP_ENV=production

RUN chown -R bun:bun /app

USER bun

ENTRYPOINT ["bun", "run", "start"]