FROM oven/bun:1.1.25-alpine

WORKDIR /app

COPY package.json bun.lockb ./

RUN bun install

COPY . .

ARG BUILD_HASH
ENV APP_BUILD_HASH=${BUILD_HASH}

ENV APP_ENV=staging

RUN chown -R bun:bun /app

USER bun

ENTRYPOINT ["bun", "run", "start"]