name: serambi

services:
  postgres:
    container_name: serambi-postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: serambi_db
    ports:
      - 5432:5432
    volumes:
      - serambi_postgres_data:/var/lib/postgresql/data
networks:
  serambi_network:
    driver: bridge
volumes:
  serambi_postgres_data:
