FROM oven/bun:1.1.24-alpine

WORKDIR /app

COPY package.json bun.lockb ./

ENV NODE_ENV=production

RUN bun install --frozen-lockfile --production

COPY . .

RUN chown -R bun:bun /app

USER bun

EXPOSE 3000/tcp

ENTRYPOINT ["bun", "run", "start"]