FROM oven/bun:1.1.25-slim

WORKDIR /app

COPY package.json bun.lockb ./

RUN bun install

COPY . .

RUN mkdir -p /app/uploads

ARG BUILD_HASH
ENV APP_BUILD_HASH=${BUILD_HASH}

RUN chown -R bun:bun /app

USER bun

ENTRYPOINT ["bun", "run", "start"]