name: serambi

services:
  postgres:
    container_name: serambi-postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: serambi_db
    ports:
      - 5432:5432
    volumes:
      - serambi_postgres_data:/var/lib/postgresql/data
  mongo:
    container_name: serambi-mongo
    image: mongo:7.0.12
    ports:
      - 27017:27017
    networks:
      - serambi_network
    volumes:
      - serambi_mongo_data:/data/db
      - serambi_mongo_config:/data/
networks:
  serambi_network:
    driver: bridge
volumes:
  serambi_postgres_data:
  serambi_mongo_data:
  serambi_mongo_config:
